version: "3.9"

services:

  api:
    image: ghcr.io/vladimirgolovanov/junior-tracker:latest
    restart: always
    env_file:
      - .env
    network_mode: host

  worker:
    image: ghcr.io/vladimirgolovanov/junior-tracker:latest
    command: python worker.py
    restart: always
    env_file:
      - .env
    network_mode: host
