"""event types new fields

Revision ID: 51cd432c0aa9
Revises: a6df98c7853b
Create Date: 2026-08-03 21:13:25.029908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cd432c0aa9'
down_revision: Union[str, Sequence[str], None] = 'a6df98c7853b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('show_in_last_events', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('event_types', sa.Column('show_in_quick_actions', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_types', 'show_in_quick_actions')
    op.drop_column('event_types', 'show_in_last_events')
    # ### end Alembic commands ###
