"""Event type parent

Revision ID: 876940a7b58a
Revises: e4b7b6f8e14a
Create Date: 2026-02-28 19:01:28.076075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '876940a7b58a'
down_revision: Union[str, Sequence[str], None] = 'e4b7b6f8e14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_types', 'event_types', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_types', type_='foreignkey')
    op.drop_column('event_types', 'parent_id')
    # ### end Alembic commands ###
