"""Event time

Revision ID: 8ec0351b55a4
Revises: 7bceeac3fc19
Create Date: 2026-02-15 21:49:18.730446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec0351b55a4'
down_revision: Union[str, Sequence[str], None] = '7bceeac3fc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('occurred_at', sa.DateTime(), nullable=False))
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('events', 'occurred_at')
    # ### end Alembic commands ###
