"""colors for event types

Revision ID: 9f46c9e16058
Revises: d3cd9130aeee
Create Date: 2026-05-06 11:43:05.901716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f46c9e16058'
down_revision: Union[str, Sequence[str], None] = 'd3cd9130aeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_types', 'color')
    # ### end Alembic commands ###
