"""Child timezones

Revision ID: b6b526834100
Revises: cd60fc353c7f
Create Date: 2026-03-11 09:36:04.798418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b526834100'
down_revision: Union[str, Sequence[str], None] = 'cd60fc353c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('childs', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('childs', 'timezone')
    # ### end Alembic commands ###
