"""Event tg message id

Revision ID: cd60fc353c7f
Revises: 876940a7b58a
Create Date: 2026-03-01 12:42:39.731235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd60fc353c7f'
down_revision: Union[str, Sequence[str], None] = '876940a7b58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tg_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'tg_message_id')
    # ### end Alembic commands ###
