"""Child model

Revision ID: d742147b16ba
Revises: d229134b03cc
Create Date: 2026-02-15 10:41:11.771815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd742147b16ba'
down_revision: Union[str, Sequence[str], None] = 'd229134b03cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('childs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_users',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['childs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id', 'user_id')
    )
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('child_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'events', 'childs', ['child_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'child_id')
    op.drop_column('events', 'user_id')
    op.drop_table('child_users')
    op.drop_table('childs')
    # ### end Alembic commands ###
