"""Event keywords, etc

Revision ID: de41fed1a6a6
Revises: 553c227711bb
Create Date: 2026-02-22 17:14:16.227273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de41fed1a6a6'
down_revision: Union[str, Sequence[str], None] = '553c227711bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('event_types', sa.Column('format', sa.String(), nullable=True))
    op.drop_constraint(op.f('events_user_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('events_user_id_fkey'), 'events', 'users', ['user_id'], ['id'])
    op.drop_column('event_types', 'format')
    op.drop_column('event_types', 'keywords')
    # ### end Alembic commands ###
