"""Child tg chat id

Revision ID: e4b7b6f8e14a
Revises: de41fed1a6a6
Create Date: 2026-02-28 18:56:02.599858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b7b6f8e14a'
down_revision: Union[str, Sequence[str], None] = 'de41fed1a6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('childs', sa.Column('tg_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('childs', 'tg_chat_id')
    # ### end Alembic commands ###
